#!/bin/bash
#Menu

echo -e "* menu      : แสดงรายการคำสั่ง"
echo -e "* usernew   : สร้างบัญชี SSH และ OpenVPN"
echo -e "* trial     : สร้างบัญชีทดลองใช้"
echo -e "* hapus     : ลบบัญชี SSH & OpenVPN"
echo -e "* cek       : ตรวจสอบการเข้าสู่ระบบของผู้ใช้"
echo -e "* userlimit : จำกัด การเข้าสู่ระบบ Dropbear การใช้งาน ให้พิมพ์ userlimit 1"
echo -e "* userlimitssh : จำกัด การเข้าสู่ระบบ sshd การใช้งาน ให้พิมพ์ userlimitssh 1"
echo -e "* member    : รายชื่อสมาชิก SSH & OpenVPN"
echo -e "* delexp    : ลบชื่อสมาชิก SSH & OpenVPN ที่วันหมดอายุแล้ว"
echo -e "* resvis    : restart service dropbear, webmin"
echo -e "              squid3, OpenVPN dan SSH"
echo -e "* reboot    : reboot VPS"
echo -e "* speedtest : speedtest VPS"
echo -e "* info      : แสดงข้อมูลระบบ"
echo -e "* about     : ติดตั้งข้อมูลสคริปต์อัตโนมัติ"
echo -e "* exit      : keluar dari Putty/Connecbot/"
echo -e "              JuiceSSH"
echo -e ""
